refactor(ui): update swagger-ui to v4
apiman/apiman pull request #2066
Opened 2022-05-23 12:42 UTC by volkflo

2022-05-31 06:37 UTC, volkflo commented
Seems to work fine now

2022-07-04 10:20 UTC, msavy commented
Rebased onto latest deps

2022-07-07 17:27 UTC, msavy commented
![image](https://user-images.githubusercontent.com/423513/177834045-58e84c6e-4d63-4662-a7f4-6ede179915c2.png)

Backgrounds of samples don't look right. Is this just a CSS thing?

2022-07-07 17:33 UTC, msavy commented
Looks like it's caused by prism.js CSS (used also for markdown editor code section).

prism.css#L7
```css
code[class*="language-"],
pre[class*="language-"] {
	color: black;  // <--- this one by the looks of it.
}
```

2022-07-07 17:38 UTC, msavy commented
I'm not sure if it was a caching issue as I can't see the issue any more!

2022-07-07 17:56 UTC, msavy requested changes
Putting on request changes, but might just be clarifications required.

2022-07-08 06:34 UTC, volkflo commented on manager/ui/war/plugins/api-manager/ts/apimanPlugin.ts
> +import "./sidebar.ts"
Mhh the view of github here is a bit strange. 
It is just an empty line that was added to the end of the file by Intellij. 
We could remove that I guess.

2022-07-08 06:34 UTC, volkflo commented on manager/ui/war/package.json
> +    "stream-browserify": "3.0.0",
That was added for polyfill, as this was suggested during build in the error log.
But I think we do not need that old polyfill stuff, so I removed it again :)

2022-07-08 07:51 UTC, merged

2022-07-08 07:51 UTC, msavy reviewed
All good. Thanks!