Importer should log file name
apiman/apiman pull request #968
Opened 2021-02-15 10:32 UTC by BastianGem

### Changes to the Importer
The importer now logs the filename at startup.

### Changes to the test framework
To test variable content in text payloads, regular expressions were enabled.

For this jUnits AssertEqual was replaced by the Java regex compiler.
In rest tests with text payload, special characters must be escaped for the regex compiler.

2021-02-15 10:35 UTC, volkflo approved these changes
LGTM :)

2021-02-15 17:14 UTC, bekihm submitted a review, later dismissed
LGTM

2021-02-26 16:34 UTC, msavy approved these changes

2021-02-26 18:18 UTC, msavy commented
@BastianGem I can't push to this branch, so [I'll just put a branch for you here](https://github.com/msavy/apiman/commits/ImporterShouldLogFileName) and you can cherry-pick the commit into the code yourself when you are ready (I also rebased it, so you might just want to push the branch over the top of your existing one). 

Another small note -- please reword your commit message to use the conventional commits pattern. You can see examples from the Apiman git log (see also https://www.conventionalcommits.org/en/v1.0.0/). 

Something like:

```
fix(importer): log file name when importing 

<If you want, a longer description, including description of the change you made to test harness>

Fixes #<some ticket number if there is one>
```

2021-02-26 18:33 UTC, msavy commented on manager/test/api/src/test/resources/test-plan-data/import/001_import.resttest
> +INFO: Starting apiman data import: .*apiman_import_migrated.*.json
I think there are some weird Windows line-endings in the original file that is causing the whole file to appear to be changed? If you can find a way of leaving that alone and only making your down change that would be great great -- but don't spend much time on it!

2021-02-26 18:34 UTC, msavy commented on manager/test/api/src/test/resources/test-plan-data/import/003_import-with-developer.resttest
> +INFO: Starting apiman data import: .*apiman_import_migrated.*.json
This regex match is definitely a useful feature 👍

2021-03-01 11:54 UTC, volkflo requested changes

2021-03-01 11:54 UTC, volkflo commented on test/common/src/main/java/io/apiman/test/common/util/TestPlanRunner.java
> +import java.util.regex.Matcher;
We do not need this anymore because of @msavy's assert

2021-03-01 11:54 UTC, volkflo commented on test/common/src/main/java/io/apiman/test/common/util/TestPlanRunner.java
> +import org.junit.ComparisonFailure;
We do not need this anymore because of @msavy's assert

2021-03-01 13:04 UTC, volkflo approved these changes

2021-03-01 13:06 UTC, merged